server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.13:1111
  # 注册到微服务提供者名称中
service-url: http://nacos-payment-provider
