server:
  port: 80
spring:
  application:
    name: cloud-order-openfeign-service #\u6D88\u8D39\u670D\u52A1
    #      sleuth +zipKin 链路监控
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
      #    采样率 在 1~0之间 1表示全部采集
    sampler:
      probability: 1
eureka:
  client:
    #true 是否将自己注册到注册中心
    register-with-eureka: false
    #true 是否从 Eureka主持中心抓取已有的注册信息 默认为 true 单节点无所谓 集群必须设置为true 才能配合ribbon使用负载均衡 fetch-registry: true
    fetch-registry: true
    service-url:
      defaultZone: http://euerka7001.com:7001/eureka/,http://euerka7002.com:7002/eureka/, http://euerka7003.com:7003/eureka/
      #设置eureka server的交互地址查询服务和注册服务   都需要依赖这个地址
      #设置feign建立连接的时间(openfeign默认支持ribbon)
feign:
  client:
    config:
      default:
        #建立连接后从服务器读取用到的时间
        readTimeout: 10000
        #建立链接使用的时间，网络正常下 两端所需要的时间
        connectTimeout: 10000
  hystrix:
    enabled: true
logging:
  level:
    #设置 feign日志级别 监控哪个接口
    com.urchin.cloud.service.PaymentFeignService: debug



