server:
  port: 80


spring:
  application:
    name: cloud-zk-order-service #\u6D88\u8D39\u670D\u52A1
  cloud:
    zookeeper:
      connect-string: 192.168.122.1:2181   #虚拟机zookeeper 服务地址 2181 是zookeeper 默认端口